# Generated by Django 2.1.4 on 2019-01-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'content', 'verbose_name_plural': 'contents'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('title',), 'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
    ]
